service: geocoding

image: aronwolf/geocoder

servers:
  web:
    - 157.180.122.172
  job:
    hosts:
      - 157.180.122.172
    cmd: bin/jobs

proxy:
  ssl: true
  host: geocoder.webcloudpower.com

registry:
  username: aronwolf
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "geocoding_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
